import requests
import json
import copy



def attempt_fix_tool_name(tool, token, http_settings):
    """Attempt to fix the tool name and revalidate."""
    tool_temp = copy.deepcopy(tool)
    tool_temp['name'] += '_autogenerated'
    valid, error_message = validate_tool(tool_temp, token, http_settings)

    return valid, tool_temp if valid else error_message


def is_html_error(message):
    return '<html' in message.lower() or '<body' in message.lower()  


def validate_tool(tool, token, http_settings):
    '''Validate a tool using the Biotools API.'''
    url = '{h}{t}{v}{f}'.format(h=http_settings['host_prod'], 
                                t=http_settings['tool'],
                                v=http_settings['validate'],
                                f=http_settings['json'])   
    headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Token ' + token
    }
    r = requests.post(url, headers=headers, data=json.dumps(tool))
    if r.ok:
        return (True, r.text)
    return (False, r.text)


def validate_tools(tools, token, http_settings):
    to_add = []
    problem_tools = []

    for tool in tools:
        valid, txt = validate_tool(tool, token, http_settings)
        
        if valid:  
            to_add.append(tool)
            continue    

        print("Tool with name:{name} has the errors: {errors}".format(name=tool['name'], errors=txt))

        if not is_html_error(txt):
            e = json.loads(txt)
            if type(e) is dict and e.get('name') != None:
                print('Error with name {name}'.format(name=tool['name']))

                valid, result = attempt_fix_tool_name(tool, token, http_settings)
                
                if valid:
                    print('The error was fixed by changing the name to {name}'.format(name=result['name']))
                    tool['name'] = result['name']
                    to_add.append(tool)
                    continue

        problem_tools.append({'tool_name':tool['name'],'error': 'html' if is_html_error(txt) else txt})    
        
    return to_add, problem_tools
